### ISSUE TITLE
How many placeholders in defaultlang.json?

### ISSUE THREAD

**Issue by Blueberryy** [3urobeat/steam-comment-service-bot#183]
Can i get full list of placeholders? I only indicated some of them: ``numberOfComments``, ``waittime``, ``availablenow``, ``untilStr``, ``numberOfVotes`` and ``failedamount``.

**Comment by HerrEurobeat** [comment]
Hey, thanks for opening an issue!  
Good question! This is something I should probably elaborate better in the customlang documentation wiki page.  
It could also be useful to indicate them in a different format, for example using the JS syntax `${name}` but that would require updating the customlang.json again. I have to think about that in the future.

I quickly went through my code searching for `lang\..+\.replace` in regex mode, these are all I could find:  
- `cmdprefix`
- `profileid`
- `remainingcooldown`
- `waittime`
- `availablenow`
- `numberOfComments`
- `failedamount`
- `untilStr`
- `thisattempt`
- `maxattempt`
- `successAmount`
- `totalAmount`
- `numberOfFavs`
- ``
- ``

**Comment by HerrEurobeat** [comment]
I hope I didn't miss anything. I have to admit that the current system of "just words that look kinda different inside the string" sucks and I'm not happy with it.  
The problem is also that these are not always really unique, meaning the word "value" I listed above could also be a word that should be translated in another string.

If you want to wait before translating I'm going to rework the variable-in-string system and let you know here

**Comment by Blueberryy** [comment]
> Hey, thanks for opening an issue! Good question! This is something I should probably elaborate better in the customlang documentation wiki page. It could also be useful to indicate them in a different format, for example using the JS syntax `${name}` but that would require updating the customlang.json again. I have to think about that in the future.
> 
> I quickly went through my code searching for `lang\..+\.replace` in regex mode, these are all I could find:
> 
> * `cmdprefix`
> * `profileid`
> * `remainingcooldown`
> * `waittime`
> * `availablenow`
> * `numberOfComments`
> * `failedamount`
> * `untilStr`
> * `thisattempt`
> * `maxattempt`
> * `successAmount`
> * `totalAmount`
> * `numberOfFavs`
> * `estimatedtime`
> * `maxOwnerComments`
> * `maxComments`
> * `pingtime`
> * `groupid`
> * `requesttime`
> * `amount`
> * `value`
> * `targetkey`
> * `oldvalue`
> * `newvalue`
> * `branchname`
> * `numberOfVotes`
> * `maxRequestAmount`
> * `cmdusage`
> * `commentcmdusage`
> * `forceFriendlistSpaceTime`
> * `unfriendtime`

thank you for the info. I just made Russian translation and i will review my text now

**Comment by Blueberryy** [comment]
@HerrEurobeat can you review if i missed something? https://github.com/Blueberryy/steam-comment-service-bot/blob/master/src/data/lang/russian.json

**Comment by HerrEurobeat** [comment]
> @HerrEurobeat can you review if i missed something? https://github.com/Blueberryy/steam-comment-service-bot/blob/master/src/data/lang/russian.json

Should be fine. Although you need to make sure `numberOfComments` & `numberOfVotes` for example in `commentprocessstarted` & `voteprocessstarted`  aren't capitalized as the replacing is case sensitive.

**Comment by HerrEurobeat** [comment]
If you want you can open a PR to merge your translation into this repository and I'll update it later when I've improved the language system.  
Thanks for making one in the first place
