### ISSUE TITLE
STEAM BOOST 

### ISSUE THREAD

**Issue by flawwear** [3urobeat/steam-comment-service-bot#198]
**Describe the solution you'd like**
A clear description of what should happen.

**Additional context**

**Comment by flawwear** [comment]
steam artwork rateup 
steam followers

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  
Artwork voting is already supported since version 2.13.0. You can use the !upvote & !downvote command to vote on sharedfiles (screenshots, artworks & guides).  
Following is already planned for version 2.14.0 but no guarantee.

**Comment by flawwear** [comment]
y
