### ISSUE TITLE
report

### ISSUE THREAD

**Issue by floiseri** [3urobeat/steam-comment-service-bot#200]
**Describe the bug**
What happened?

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

**Comment by floiseri** [comment]
Sorry but an error occurred while loading the sharedfile you have provided: TypeError: Cannot read properties of undefined (reading 'children')

**Comment by floiseri** [comment]
i get this error every time

**Comment by floiseri** [comment]
i get this error every time

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue!  
Can you share the link to the sharedfile you are trying to provide?  
This error sounds like Steam left out some data in their response which would be weird

**Comment by floiseri** [comment]
I deleted the 
artowork

**Comment by 3urobeat** [comment]
Okay...  
So I guess this can be closed then? Loading sharedfiles works fine for me.  
Thanks for reporting anyways!  
If you re-encounter this error feel free to reopen this issue.

**Comment by floiseri** [comment]
ok ty
