### ISSUE TITLE
Sorry but an error occurred while loading the sharedfile you have provided: TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by fixhel** [3urobeat/steam-comment-service-bot#201]
**Describe the bug**
What happened?

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

**Comment by fixhel** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2943367936

**Comment by 3urobeat** [comment]
This should be fixed by 352ca46 & c6a7c34. I'm going to leave this issue open until the fix is available in the master branch in version 2.13.6.

**Comment by 3urobeat** [comment]
Version 2.13.6 is now out on the master branch. Your bot will update automatically but you can force it to update now by running the `!update` command.  
Thanks again for reporting this issue!
