### ISSUE TITLE
cs go commands bot ? 

### ISSUE THREAD

**Issue by jahreintr** [3urobeat/steam-comment-service-bot#204]
**Describe the solution you'd like**
A clear description of what should happen.

**Additional context**

**Comment by jahreintr** [comment]
+ commends

**Comment by jahreintr** [comment]
s

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  
This has been suggested quite a few times already but I have no plans to work on CS:GO related features at the moment for various reasons, sorry.

**Comment by jahreintr** [comment]
ok
