### ISSUE TITLE
Feature Request: Game Review and Workshop Follow

### ISSUE THREAD

**Issue by boschenk** [3urobeat/steam-comment-service-bot#207]
Description:
I would like to propose a new feature for consideration in the upcoming versions of your project.

Version 2.15 Enhancement: Game Review
In the new version 2.15, I suggest implementing a Game Review feature ("Rate Up," "Rate Down," and "Funny") similar to the rating system on Steam. 

Version 2.14 Enhancement: Workshop Follow & Curator* Follow
I propose adding a Workshop Follow feature. (Already requested)

Reference:
*A good example of a successful curator can be found on the Steam platform, particularly with the PC Gamer curator page: https://store.steampowered.com/curator/1850-PC-Gamer/

Your consideration and prompt action in implementing these features would be greatly appreciated.

**Comment by 3urobeat** [comment]
Hey, thanks for the (very well written) suggestion!  
I will take a look at how (and if) I'll be able to implement those features and report back.  
I don't think the `node-steamcommunity` library provides functions for these features so I'd have to reverse engineer the requests myself.

I'm quite busy at the moment so I sadly won't be able to start working on it instantly but I'll see when I'll find some time.

**Comment by jahreintr** [comment]
+

**Comment by AlRampage** [comment]
i need

**Comment by 3urobeat** [comment]
I have now added support for following & unfollowing users as mentioned in #163.
I'll post another comment when the change is out in Version 2.14.0 on the master branch and will keep this issue open until I have worked on the review support you mentioned.

**Comment by junmie** [comment]
/

**Comment by 3urobeat** [comment]
Version 2.14 is out on master which adds support for following users/workshops/curators.  
Check out the release notes [here](https://github.com/3urobeat/steam-comment-service-bot/releases/tag/2.14.0)!

**Comment by 3urobeat** [comment]
Commenting and voting on reviews has now been implemented.  
I'll keep this issue open until this feature is out on the master branch.

**Comment by 3urobeat** [comment]
Version 2.15 is now out on the master branch and adds support for this suggestion.
Check out the release notes [here](https://github.com/3urobeat/steam-comment-service-bot/releases/tag/2.15.0)!
