### ISSUE TITLE
çok fazla hata veriyor

### ISSUE THREAD

**Issue by ferolif** [3urobeat/steam-comment-service-bot#222]
**Describe the bug**
What happened?

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

benim 6 tane hesabım var onları kullanıyorum ama hata veriyor durmadan. aynı hatayı veriyor -+"çok fazla yorum attın"" diyor

türk var mı cevap verecek 
cevap verecek biri var mı ? 
6 tane hesabım 0 level o yüzden mi

**Comment by ferolif** [comment]
bide rateup hata veriyor like atamıyorum

**Comment by 3urobeat** [comment]
Sorry, I do not speak Turkish.  

**Original issue, translated:**
> çok fazla hata veriyor

gives too many errors

> benim 6 tane hesabım var onları kullanıyorum ama hata veriyor durmadan. aynı hatayı veriyor -+"çok fazla yorum attın"" diyor
>
> türk var mı cevap verecek
> cevap verecek biri var mı ?
> 6 tane hesabım 0 level o yüzden mi

I have 6 accounts and I use them but it keeps giving errors. It gives the same error -+"You posted too many comments"

Is there any Turk to answer?
Is there anyone to answer?
Is that why I have 6 accounts and they are level 0?

&nbsp;

Please look at the wiki beforehand, this error message is listed and explained on the [errors documentation page](https://github.com/3urobeat/steam-comment-service-bot/blob/master/docs/wiki/errors_doc.md#steam-errors).  

As you can see, this error is commonly returned by Steam if your accounts are making too many comments in a short timeframe.  
Steam returns this error intentionally to reduce spam. Therefore this is not a bug.

You can reduce the likelihood of this error appearing by increasing your commentdelay, using proxies (to spread your accounts over multiple IP addresses) and requesting less comments at a time.  
Proxies are strongly recommended as they make the biggest impact - from personal experience you can send 100 comments total in ~7.5 minutes with 30 accounts (= ~3.3 comments per account) if you are using at least 15 proxies (= 2 accounts per proxy) without errors.

I'm not sure if the Steam level has an effect on how fast your accounts can get a cooldown, but I don't think there is an explicit connection. Maybe older Steam accounts (who appear more trustworthy) can comment more at a time but I don't have any evidence, just a slight feeling. But whatever, all my bot accounts are also just level 0 so this isn't something to worry about.

**Comment by 3urobeat** [comment]
Maybe I should ask - what are your current settings?
- You said 6 accounts
- How many proxies?
- requestDelay in your config?
- How many comments do you request at a time?

**Comment by ferolif** [comment]
tamam sıkıntı yok teşekkür ederim

**Comment by ferolif** [comment]
steam takipçisi komutu nedir

**Comment by ferolif** [comment]
hesaplarım nsanırım kısıtlama yedi? bilmiyoru m

**Comment by 3urobeat** [comment]
> tamam sıkıntı yok teşekkür ederim

ok no problem thank you

---

:)

&nbsp;

> steam takipçisi komutu nedir

What is the steam follower command?

---

`!follow`  
Again, this is also documented in the wiki: [Commands page](https://github.com/3urobeat/steam-comment-service-bot/blob/master/docs/wiki/commands_doc.md)

&nbsp;

> hesaplarım nsanırım kısıtlama yedi? bilmiyoru m

I think my accounts are restricted? I don't know

---

I don't know either. As documented in the wiki on the [Steam limitations page](https://github.com/3urobeat/steam-comment-service-bot/blob/master/docs/wiki/steam_limitations.md), accounts count as limited if they have spent less than $5 on the Steam Store.  
Please see the list on the linked wiki page for reference what limited accounts can and cannot do.

**Comment by 3urobeat** [comment]
I hope I was able to answer your questions. If not, please reopen.  
If you've got any other questions please feel free to open another issue!
