### ISSUE TITLE
Support for mass requests

### ISSUE THREAD

**Issue by Literaty** [3urobeat/steam-comment-service-bot#225]
**Describe the solution you'd like**
A clear description of what should happen.

**Additional context**
hey
I want to rate up many shipments at the same time
But it has time. keeps me waiting. I'm only having one done and I'm waiting for it to be finished.

**Comment by 3urobeat** [comment]
Hey!  
I don't have any mass-request plans at the moment.  
This might be an idea for a plugin at some point because I'd like to keep the core project focused on being a service for fulfilling requests for users.  
idk when and if though

**Comment by Literaty** [comment]
Ok. I sent a message on steam. By the way, congratulations, it is a nice software.
