### ISSUE TITLE
ㅤㅤㅤㅤ  

### ISSUE THREAD

**Issue by feadelgemz** [3urobeat/steam-comment-service-bot#226]
**Describe the bug**
What happened?

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

**Comment by feadelgemz** [comment]
I have a lot of game reviews. I want to boost them

**Comment by 3urobeat** [comment]
Duplicate of #207?  
Review support will be implemented in v2.15

**Comment by 3urobeat** [comment]
Thank you for the donation :heart:

**Comment by feadelgemz** [comment]
@

**Comment by feadelgemz** [comment]
❤
