### ISSUE TITLE
Game review support

### ISSUE THREAD

**Issue by ea151** [3urobeat/steam-comment-service-bot#231]
**Question or issue you are experiencing**
Please explain your question here. If you've got an error or something else related, then please include it here as well.

**Additional information**
Please add any other information here if you have some.

i need review boost

**Comment by ea151** [comment]
https://steamcommunity.com/id/emncglr/recommended/

**Comment by 3urobeat** [comment]
Hey, this was already requested in #207 and is planned for version 2.15 ^^
