### ISSUE TITLE
hesap satın almak istiyorum boostlarım için. hesap satmak isteyen mesaj atsın bana benle iletişime gececek var mı 

### ISSUE THREAD

**Issue by banevav** [3urobeat/steam-comment-service-bot#233]
hesap satın almak istiyorum boostlarım için. hesap satmak isteyen mesaj atsın bana benle iletişime gececek var mı 

1 hesap için 10 tl verebilirim 
10 hesap için 120 tl

**Comment by banevav** [comment]
-5 dolar yüklenmiş hesaplar lazım

**Comment by 3urobeat** [comment]
Hey, this is not a marketplace, nor do I sell accounts. (And I also do not speak Turkish)  
Please only use issues for reporting bugs or requesting help.  
Closing as invalid.

**Comment by banevav** [comment]
sryy
