### ISSUE TITLE
a question about steam guard

### ISSUE THREAD

**Issue by pushkinb** [3urobeat/steam-comment-service-bot#243]
Hi, I just started using your program today. please tell me, does it save sessions so that I don't have to enter Steam Guard on each account every time?

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue!  

Yes, sessions for accounts with **E-Mail Steam Guard** are saved.  
You only need to input your Steam Guard Code the first time and after ~200 days of inactivity.

Sessions for accounts with Mobile Steam Guard are always invalidated after logout.

All of this is enforced by Steam themselves.

**Comment by pushkinb** [comment]
Thanks, i love you!
