### ISSUE TITLE
Programm don't work with proxy

### ISSUE THREAD

**Issue by pushkinb** [3urobeat/steam-comment-service-bot#248]
**Question or issue you are experiencing**
Please explain your question here. If you've got an error or something else related, then please include it here as well.

Hello, i can't use HTTPS proxy on programm. She close with message "Proxy timeout",  but proxy work.

**Additional information**
Please add any other information here, if you have some.

217.29.63.240:12980 Login: Szc0ja Password: 145Ne4
I buy this HTTPS proxy for 3 days

**Comment by 3urobeat** [comment]
I assume you have gotten your proxies working. If not, feel free to reopen.

**Comment by pushkinb** [comment]
Hi, sorry for the long answer. when I try to use a proxy, I encounter an endless download
![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/d0b82d4c-3417-44e0-b839-8b8275dd9179)

my proxy file looks like this:
![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/f3a47e59-663c-4a8e-90ae-20c0d030f38d)

could this problem be due to the fact that my proxies are https and not http?

**Comment by 3urobeat** [comment]
Perhaps, yeah, that could be the cause.  
The proxies are just passed on to the steam-user and steamcommunity module by the bot.  

I think they only support http proxies and I don't know which behaviour to expect when you provide a https proxy.  
Please try normal http proxies, those work for me as well and are expected by both modules.

**Comment by pushkinb** [comment]
ok, I'll try to buy an http proxy and run the program with them, thanks

**Comment by pushkinb** [comment]
![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/0adc79c1-fd26-4fcc-a1b6-470a59db3e26)

**Comment by pushkinb** [comment]
oh, I can't find paid http proxies, so I found free ones, but they don't have a password, so I don't know what to put in the password place

**Comment by pushkinb** [comment]
![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/eb9ab99c-d1cd-46ba-bd12-fbb5338e6129)
after this error, the program closes, please tell me what I'm doing wrong, I'll send you my proxies and a screenshot of how I uploaded them to a file proxies.txt
![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/79dd7444-54a4-4e1b-9a79-e685c3dbacfd)
![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/ec526510-256a-444e-9bd1-83af8ca41006)

**Comment by 3urobeat** [comment]
Ah, okay, I didn't even think of IPv6  
Good to hear that you have found working proxies.

I should try to improve the error messages you get when trying to use unsupported proxies, unhandled rejections are not great to see

**Comment by 3urobeat** [comment]
This was actually a bug where the bot failed to use HTTP proxies that were not preceded by `http://`.

The fix will be included in Version 2.15.3. I'll leave this issue open until the update is out on the master branch.
