### ISSUE TITLE
request recharge time is too long

### ISSUE THREAD

**Issue by pushkinb** [3urobeat/steam-comment-service-bot#250]
**Question or issue you are experiencing**
Please explain your question here. If you've got an error or something else related, then please include it here as well.

hi, when I use a command, sometimes I encounter failed, and when I need an even amount I want to reuse it, but I don't understand why the program asks to wait such a long time

![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/9c5f57c0-f94e-4bbb-b358-b9cf0b41f5cd)

my config:
![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/b17029fd-f7f2-4725-b71e-f4b0d72adba5)

**Additional information**
Please add any other information here, if you have some.

**Comment by pushkinb** [comment]
I want to reduce this delay but I can't find such a setting.

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.  

When encountering "HTTP Error 429" or "you've been posting too frequently, and can't make another post right now" the bot adds 5 minutes to the length of the request (basically preventing the accounts from being used for another 5 minutes).  
This seems to be hardcoded. 

I'm not exactly sure why you are getting a 40 minute cooldown when you have both cooldowns disabled in the config.  
Just from a quick glance at the code, it could be that the request-length-extension-thing stacks, which I don't think is intended.

How many comments failed in that request from your first screenshot? Knowing that could maybe answer that theory.

**Comment by pushkinb** [comment]
Hi, I only got 10 errors at that moment.
![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/a351fa2b-da89-4a18-b4e9-0ae4a0ef0a46)

**Comment by 3urobeat** [comment]
Depending on which errors you encountered my theory might make sense.  
I'll test this when working on the next update. The extended cooldown should not stack, that is not intended and will be fixed if it is the case.

**Comment by 3urobeat** [comment]
This has been fixed, the 5 min IP cooldown penalty will only be applied once to a request instead of stacking incorrectly.

The fix will be included in Version 2.15.3. I'll leave this issue open until the update is out on the master branch.

**Comment by 3urobeat** [comment]
Version 2.15.3 is now out which fixes the issue.
